import {
  AccessTimeOutlined,
  AddOutlined,
  ArticleOutlined,
  DashboardOutlined,
  DeleteOutlined,
  DescriptionOutlined,
  DesktopWindowsOutlined,
  HelpOutlineOutlined,
  KeyboardDoubleArrowRightOutlined,
  LiveHelpOutlined,
  LocalLibraryOutlined,
  EmailOutlined,
  NotificationsNoneOutlined,
  Person2Outlined,
  SettingsOutlined,
  TrendingUpOutlined,
  VisibilityOutlined,
  VisibilityOffOutlined,
  WorkOutlineOutlined
} from "@mui/icons-material";

export enum IconType {
  Add = "add",
  Article = "article",
  Business = "business",
  Dashboard = "dashboard",
  Delete = "delete",
  Desktop = "desktop",
  Email = "email",
  File = "file",
  Forward = "forward",
  Help = "help",
  Library = "library",
  Live = "live",
  Notifications = "notifications",
  Time = "time",
  Person = "person",
  Settings = "settings",
  TrendingUp = "trendingup",
  Visibility = "visibility",
  VisibilityOff = "visibilityoff",
  Work = "work"
}

export const iconLookup: Record<IconType, typeof AddOutlined> = {
  add: AddOutlined,
  article: ArticleOutlined,
  business: WorkOutlineOutlined,
  dashboard: DashboardOutlined,
  delete: DeleteOutlined,
  desktop: DesktopWindowsOutlined,
  email: EmailOutlined,
  file: DescriptionOutlined,
  forward: KeyboardDoubleArrowRightOutlined,
  help: HelpOutlineOutlined,
  library: LocalLibraryOutlined,
  live: LiveHelpOutlined,
  notifications: NotificationsNoneOutlined,
  time: AccessTimeOutlined,
  person: Person2Outlined,
  settings: SettingsOutlined,
  trendingup: TrendingUpOutlined,
  visibility: VisibilityOutlined,
  visibilityoff: VisibilityOffOutlined,
  work: WorkOutlineOutlined
};
